name: Build and test

on:
  workflow_call:

jobs:
  build:
    name: Build Ratings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.76.0
          components: clippy, rustfmt

      - name: Install additional build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config protobuf-compiler
      - name: Check code format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

      - name: Lint code
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      - name: Setup and Run Tests
        run: |
          cp example.env .env
          cargo install cargo-make
          cargo make db-up
          cargo make full-test
